baseURL = "https://mertkavi.com"
publishDir = "docs"

[permalinks]
  posts = "/:title/"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

googleAnalytics = "G-DHZD8906YW"

[outputs]
  home = ["HTML", "RSS", "JSON"]
