languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Mert Kavi"
description = "Personal website of Mert Kavi. My thoughts about information software, data, and AI."
copyright = "Copyright © 2024 Mert Kavi"

dateFormat = "2 January 2006"

[params.author]
  name = "Mert Kavi"
  image = "img/author.jpg"
  headline = "On software, data, and AI."
  bio = "Software, Data, and AI Professional"
  links = [
     { email = "mailto:mertkavi@gmail.com" },
     { linkedin = "https://linkedin.com/in/mertkavi" }
   ]